In [8]:
import numpy as np
import pandas as pd

Copy the file(Data Source) from the command prompt to the folder running this workbook and try below to introduce your file name/

In [9]:
excelfile=r"Assignment_2_Data_and_Template.xlsx";
excelfile

'Assignment_2_Data_and_Template.xlsx'

In [10]:
def getSheetNames(excelfile):
    from pandas import ExcelFile
    return (ExcelFile(excelfile)).sheet_names

Once the file is there and the function above is defined, then the next line should list your sheet names in the excel file.

In [11]:
sheets=getSheetNames(excelfile);
sheets

[u'Data',
 u'Female Histogram',
 u'Male Histogram',
 u'Bayesian',
 u'Queries',
 u'Reconstructed Female Histogram',
 u'Reconstructed Male Histogram',
 u'Observations']

In [12]:
def readExcelSheet1(excelfile):
    from pandas import read_excel
    return (read_excel(excelfile)).values

In [7]:
def readExcelRange(excelfile,sheetname="Sheet1",startrow=1,endrow=1,startcol=1,endcol=1):
    from pandas import read_excel
    values=(read_excel(excelfile, sheetname,header=None)).values;
    return values[startrow-1:endrow,startcol-1:endcol]

In [15]:
def readExcel(excelfile,**args):
    if args:
        data=readExcelRange(excelfile,**args)
    else:
        data=readExcelSheet1(excelfile)
    if data.shape==(1,1):
        return data[0,0]
    elif (data.shape)[0]==1:
        return data[0]
    else:
        return data

In [16]:
def writeExcelData(x,excelfile,sheetname,startrow,startcol):
    from pandas import DataFrame, ExcelWriter
    from openpyxl import load_workbook
    df=DataFrame(x)
    book = load_workbook(excelfile)
    writer = ExcelWriter(excelfile, engine='openpyxl') 
    writer.book = book
    writer.sheets = dict((ws.title, ws) for ws in book.worksheets)
    df.to_excel(writer, sheet_name=sheetname,startrow=startrow-1, startcol=startcol-1, header=False, index=False)
    writer.save()
    writer.close()

### __numpy.array__
_numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)<br>_
* You may use function __"ReadExcel"__ to read your data into the variable called __"Data"__
* You may refer to the cells inside your __Data__ variable by using __data[1,2]__ for the value in row 1 and column 2
* In order to read a full column regardless of row number you may use __":"__ eg. __data[:,1]__
* Note that the first column (A) is index 0

In [29]:
data=readExcel(excelfile)
#X=np.array(data[:,1],dtype=float)
#X
data[1,:]

array([u'Male', 71.0, 23.5], dtype=object)

In [48]:
X=np.array(data[:,1],dtype=float)
X[:10]

array([ 68.,  71.,  73.,  64.,  68.,  59.,  73.,  75.,  65.,  69.])

using a for to read the data in string format

In [37]:
T=np.array([str(g) for g in data[:,0]])
T

array(['Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male',
       'Male', 'Female', 'Female', 'Male', 'Female', 'Female', 'Female',
       'Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female',
       'Male', 'Female', 'Female', 'Female', 'Female', 'Female', 'Male',
       'Male', 'Female', 'Female', 'Male', 'Male', 'Male', 'Female',
       'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Male',
       'Male', 'Female', 'Female', 'Female', 'Male', 'Female', 'Female',
       'Female', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Male',
       'Female', 'Female', 'Male', 'Female', 'Male', 'Male', 'Female',
       'Male', 'Female', 'Female', 'Male', 'Male', 'Male', 'Male',
       'Female', 'Ma

In order to read a 2D data you may use __data[:,1:]__

In [57]:
data=readExcel(excelfile)
X=np.array(data[:,1:],dtype=float);
T=np.array(data[:,0],dtype=str);
X[:,0]

array([ 68.  ,  71.  ,  73.  ,  64.  ,  68.  ,  59.  ,  73.  ,  75.  ,
        65.  ,  69.  ,  69.  ,  64.  ,  67.  ,  67.  ,  69.  ,  73.  ,
        62.  ,  69.  ,  64.  ,  74.  ,  73.  ,  66.  ,  74.  ,  73.  ,
        69.  ,  64.  ,  67.  ,  60.  ,  75.  ,  64.  ,  67.  ,  67.  ,
        66.  ,  62.  ,  72.  ,  71.  ,  61.  ,  63.  ,  66.  ,  71.  ,
        71.  ,  66.  ,  70.  ,  67.  ,  69.  ,  67.  ,  68.  ,  67.  ,
        68.  ,  71.  ,  70.  ,  74.  ,  60.  ,  65.  ,  72.  ,  76.  ,
        66.  ,  64.5 ,  71.  ,  69.  ,  64.  ,  65.  ,  74.  ,  68.  ,
        68.  ,  69.  ,  68.  ,  67.  ,  61.5 ,  63.  ,  67.  ,  71.  ,
        73.  ,  63.  ,  61.  ,  67.  ,  72.  ,  72.  ,  68.  ,  66.  ,
        67.  ,  67.  ,  72.  ,  67.5 ,  63.75,  72.  ,  69.  ,  68.  ,
        71.  ,  71.  ,  63.  ,  70.  ,  68.  ,  67.5 ,  75.  ,  74.  ,
        71.  ,  71.  ,  64.  ,  71.  ,  69.  ,  65.  ,  69.  ,  63.  ,
        70.  ,  71.  ,  64.  ,  63.  ,  65.  ,  66.  ,  66.  ,  65.  ,
      

2- Construct separate 2D histograms for male and female heights. You decide on the number of bins to use, making sure there is sufficient resolution and bin-filling. Represent height in rows, and handspan in columns -- both in ascending order of magnitude of feature. Do not use a built-in histogram program. <br>
* __Hint:__ Assume that the data is given as 𝑋={{ℎ_1,𝑠_1 },{ℎ_2,𝑠_2 },{ℎ_3,𝑠_3 },…} where the heights are ℎ_𝑖, the handspans are 𝑠_𝑖 and the genders are given as G={𝑔_1,𝑔_2,𝑔_3,…,𝑔_𝑁 }.


In [63]:
T[:10]

array(['Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male',
       'Male', 'Female', 'Female'], 
      dtype='|S6')

* __Hint 02: __ <br>
Construct separate 2D histograms for the two classes. One way to do this is to first initialize (with zeros) two matrices $𝐻_𝐹$ and $𝐻_𝑀$, each of size 𝐵×𝐵. <br> 
Next, compute the minimum and maximum of each of the features found in the training data (irrespective of class). Let us call these limits $ℎ_{min}$, $ℎ_{max}$, $𝑠_{min}$, and $𝑠_{max}$. <br>
The matrices $𝐻_𝐹$ and $𝐻_𝑀$ will now be subjected to a sequence of updating operations till the histograms are built up.


In [24]:
#This is how to initiate a DxD array in python but we won't use this (FYI Only)
twod_list = []                    
for i in range (0, 3): 
    new = []                
    for j in range (0, 5): 
        new.append('ddd')       
    twod_list.append(new)  
twod_list

[['ddd', 'ddd', 'ddd', 'ddd', 'ddd'],
 ['ddd', 'ddd', 'ddd', 'ddd', 'ddd'],
 ['ddd', 'ddd', 'ddd', 'ddd', 'ddd']]

In [27]:
#numPy got it's own way of initiating arrays
#numpy.zeros(shape, dtype=float, order='C')
#Return a new array of given shape and type, filled with zeros.
HF=np.zeros(2).astype('int32');
HF

array([0, 0], dtype=int32)

In [91]:
#for a nD array eg 2x2
#pay attention to double brackets
# Visit https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.zeros.html

HF=np.zeros((B,B)).astype('int32');
HF
HM=np.zeros((B,B)).astype('int32');

In [31]:
# this will build a 1D Histogram Classifier (FYI only)
def BuildHistogramClassifier(X,T,B,xmin,xmax):
    HF=np.zeros((B,2)).astype('int32');
    HM=np.zeros((B,2)).astype('int32');
    binindices=(np.round(((B-1)*(X-xmin)/(xmax-xmin)))).astype('int32');
    for i,b in enumerate(binindices):
        if T[i]=='Female':
            HF[b]+=1;
        else:
            HM[b]+=1;
    return [HF,HM]

In [69]:
B=8
xmin = np.amin(X, axis=0)
xmax = np.amax(X, axis=0)
hmin = xmin[0]
hmax = xmax[0]
smin = xmin[1]
smax = xmax[1]


* __Hint 03__ <br>
For every feature vector {$ℎ_𝑖$,$𝑠_𝑖$} pair belonging to the training set, do:<br>
    * Transform {$ℎ_𝑖$,$𝑠_𝑖$ } to row-column indices {𝑟,𝑐 } using
    	$$𝑟=𝑅𝑂𝑈𝑁𝐷((𝐵−1)((ℎ_𝑖−ℎ_{min})/(ℎ_{max}−ℎ_{min} )))$$
	$$𝑐=𝑅𝑂𝑈𝑁𝐷((𝐵−1)((𝑠_𝑖−𝑠_{min})/(𝑠_{max}−𝑠_{min} )))$$


In [60]:
# now I've put all the above information together to build a 2DHistogram
def Build2DHistogramClassifier(X,T,B,xmin,xmax):
    hmin = xmin[0]
    hmax = xmax[0]
    smin = xmin[1]
    smax = xmax[1]
    HF=np.zeros((B,)).astype('int32');
    HM=np.zeros((B,)).astype('int32');
    #Below creates bin indexes 𝑏=𝐵𝐹(𝑥) to map a given sample 𝑥 to a bin index 𝑏.
    # So if the given sample is of a height nature it's allocated to row (r)
    # and if it's of a hand span nature, it is related to column (c)
    binindices_r=(np.round(((B-1)*(X[:,0]-hmin)/(hmax-hmin)))).astype('int32');
    binindices_c=(np.round(((B-1)*(X[:,1]-smin)/(smax-smin)))).astype('int32');
    # the enumerate in 2D please share your thoughts
    for i,b in enumerate(binindices_r):
        if T[i]=='Female':
            HF[b]+=1;
        else:
            HM[b]+=1;
    #return [HF,HM]
    return binindices_r

__What does bin indices does?__ <br>
lets say you got 10 people of 10 different heights and you wan't to categorize them in 3 bins. when you run the bin index formula, you basically map each height to one of 3 bins.

In [61]:
binic = Build2DHistogramClassifier(X,T,B,xmin,xmax);

In [62]:
binic

array([4, 5, 5, 2, 4, 1, 5, 6, 3, 4, 4, 2, 3, 3, 4, 5, 2, 4, 2, 6, 5, 3, 6,
       5, 4, 2, 3, 1, 6, 2, 3, 3, 3, 2, 5, 5, 1, 2, 3, 5, 5, 3, 4, 3, 4, 3,
       4, 3, 4, 5, 4, 6, 1, 3, 5, 6, 3, 2, 5, 4, 2, 3, 6, 4, 4, 4, 4, 3, 2,
       2, 3, 5, 5, 2, 1, 3, 5, 5, 4, 3, 3, 3, 5, 4, 2, 5, 4, 4, 5, 5, 2, 4,
       4, 4, 6, 6, 5, 5, 2, 5, 4, 3, 4, 2, 4, 5, 2, 2, 3, 3, 3, 3, 4, 0, 5,
       2, 3, 4, 2, 3, 3, 5, 6, 4, 4, 3, 2, 3, 6, 5, 2, 6, 4, 6, 2, 4, 6, 2,
       4, 3, 6, 6, 5, 5, 2, 3, 3, 4, 3, 5, 7, 2, 4, 2, 2, 5, 6, 4, 4, 2, 2,
       3, 1, 5, 3, 4, 5], dtype=int32)

__Hint 04:__ <br>
If gender $𝑔_𝑖=𝐹$, update $𝐻_𝐹$ as $𝐻_𝐹 [𝑟,𝑐]=𝐻_𝐹 [𝑟,𝑐]+1$. Otherwise, update $𝐻_𝑀$ as $𝐻_𝑀 [𝑟,𝑐]=𝐻_𝑀 [𝑟,𝑐]+1$.


In [87]:
B=8
binindices_r=(np.round(((B-1)*(X[:,0]-hmin)/(hmax-hmin)))).astype('int32');
binindices_c=(np.round(((B-1)*(X[:,1]-smin)/(smax-smin)))).astype('int32');
for i,r in enumerate(binindices_r):
    for i,c in enumerate(binindices_c):
        if T[i]=='Female':
            HF[r,c:]+=1;
        else:
            HM[r,c:]+=1;
[HF,HM]

[array([[ 186,  210],
        [1116, 1260],
        [5766, 6510],
        [7052, 7964],
        [7212, 8148],
        [6262, 7078],
        [3128, 3536],
        [ 184,  208]], dtype=int32), array([[ 234,  236],
        [1404, 1416],
        [7254, 7316],
        [8908, 8984],
        [9168, 9246],
        [8018, 8086],
        [4012, 4046],
        [ 236,  238]], dtype=int32)]

In [93]:
B=6
binindices_r=(np.round(((B-1)*(X[:,0]-hmin)/(hmax-hmin)))).astype('int32');
binindices_c=(np.round(((B-1)*(X[:,1]-smin)/(smax-smin)))).astype('int32');
for i,g in enumerate(T):
    if T[i] =='Female':
        HF[binindices_r[i],binindices_c[i]]+=1;
    else:
        HM[binindices_r[i],binindices_c[i]]+=1;
[HF,HM]

[array([[ 2,  0,  1,  0,  0,  0,  0,  0],
        [ 1, 11,  9,  4,  0,  0,  0,  0],
        [ 1, 15, 43, 16,  5,  0,  0,  0],
        [ 0,  3, 16, 24,  5,  0,  0,  0],
        [ 0,  0,  4,  9,  4,  2,  0,  0],
        [ 0,  0,  1,  1,  1,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  1,  7,  1,  0,  0,  0],
        [ 0,  1,  4, 22, 13,  1,  0,  0],
        [ 0,  1,  5, 12, 24,  8,  3,  0],
        [ 0,  0,  0,  5, 17,  8,  5,  0],
        [ 0,  0,  0,  1,  3,  1, 12,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  1]], dtype=int32)]