In [1]:
import numpy as np

In [42]:
import matplotlib.pyplot as plt

In [11]:
excelfile=r"Assignment_1_Data_and_Template.xlsx";
excelfile

'Assignment_1_Data_and_Template.xlsx'

In [7]:
sheets=getSheetNames(excelfile);
sheets

NameError: name 'getSheetNames' is not defined

In [6]:
def readExcelSheet1(excelfile):
    from pandas import read_excel
    return (read_excel(excelfile)).values

In [72]:
excelfile.head(10);

AttributeError: 'str' object has no attribute 'head'

In [18]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
 
df = pd.read_excel('Assignment_1_Data_and_Template.xlsx', sheetname='Data')
 
print("Column headings:")
print(df.columns)

Column headings:
Index([u'Height_Feet', u'Height_Inches', u'Gender'], dtype='object')


In [19]:
def readExcelSheet1(excelfile):
    from pandas import read_excel
    return (read_excel(excelfile)).values

In [20]:
def readExcelRange(excelfile,sheetname="Sheet1",startrow=1,endrow=1,startcol=1,endcol=1):
    from pandas import read_excel
    values=(read_excel(excelfile, sheetname,header=None)).values;
    return values[startrow-1:endrow,startcol-1:endcol]

In [21]:
def readExcel(excelfile,**args):
    if args:
        data=readExcelRange(excelfile,**args)
    else:
        data=readExcelSheet1(excelfile)
    if data.shape==(1,1):
        return data[0,0]
    elif (data.shape)[0]==1:
        return data[0]
    else:
        return data

In [22]:
def writeExcelData(x,excelfile,sheetname,startrow,startcol):
    from pandas import DataFrame, ExcelWriter
    from openpyxl import load_workbook
    df=DataFrame(x)
    book = load_workbook(excelfile)
    writer = ExcelWriter(excelfile, engine='openpyxl') 
    writer.book = book
    writer.sheets = dict((ws.title, ws) for ws in book.worksheets)
    df.to_excel(writer, sheet_name=sheetname,startrow=startrow-1, startcol=startcol-1, header=False, index=False)
    writer.save()
    writer.close()

In [28]:
def getSheetNames(excelfile):
    from pandas import ExcelFile
    return (ExcelFile(excelfile)).sheet_names

In [23]:
excelfile=r"Assignment_1_Data_and_Template.xlsx";

In [29]:
sheets=getSheetNames(excelfile);sheets

[u'Data',
 u'Classifiers - Full Data',
 u'Classifiers - Partial Data',
 u'Observations']

In [36]:
data=readExcel(excelfile)
X=np.array(data[:,0]*12+data[:,1],dtype=float)
T=np.array([str(g) for g in data[:,2]])
X50=X[:50]
T50=T[:50]

In [39]:
X[:50]

array([ 70.,  76.,  70.,  69.,  67.,  72.,  71.,  69.,  65.,  62.,  67.,
        71.,  70.,  75.,  74.,  58.,  69.,  64.,  74.,  76.,  69.,  73.,
        66.,  74.,  62.,  62.,  65.,  71.,  64.,  74.,  64.,  69.,  72.,
        63.,  63.,  55.,  62.,  65.,  80.,  64.,  66.,  61.,  71.,  66.,
        68.,  66.,  69.,  66.,  56.,  59.])

Whats Queries?

... Queries are users **feature vector** given to a __classifier__ to get output of predictions!

In [34]:
queries=(readExcel(excelfile,
                  sheetname='Classifiers - Full Data',
                  startrow=17,
                  endrow=17,
                  startcol=2,
                  endcol=7)).astype(float);
queries

array([ 55.,  60.,  65.,  70.,  75.,  80.])

Here is the actual code you need to put in:

In [32]:
xmin=1;xmax=2;

HF=np.arange(32);HM=np.arange(32);
muF=1.2;muM=3.4;
sigmaF=5.6;sigmaM=7.8;
NF=11;NM=22;
resultHprob=np.arange(0,1,1/6);
resultBprob=np.arange(1,0,-1/6);

HF50=np.arange(32);HM50=np.arange(32);
muF50=1.2;muM50=3.4;
sigmaF50=5.6;sigmaM50=7.8;
NF50=11;NM50=22;
resultHprob50=np.arange(0,1,1/6);
resultBprob50=np.arange(1,0,-1/6);

ZeroDivisionError: division by zero

Solution steps
Histogram construction (use the method described in Lecture 1)
1. Import data from the file. Preprocess to convert samples given in feet and inches to proper decimal representation. Let 𝑋={𝑥_0,𝑥_1,𝑥_2,…,𝑥_(𝑁−1) } represent the heights and 𝑇={𝑡_0,𝑡_1,𝑡_2,…,𝑡_(𝑁−1) } represent the corresponding target class labels (genders).
2. Set the number of histogram bins 𝐵=32.
3. Find 𝑥_"min"  and 𝑥_"max"  , the minimum and maximum of the set 𝑋 (which includes samples from both genders).
4. Create a function 𝑏=𝐵𝐹(𝑥) to map a given sample 𝑥 to a bin index 𝑏. (Step 3 in the previous slide, make sure you use the entire data to calculate 𝑥_"min"  and 𝑥_"max" )
5. Use the above function to find the two histograms 𝐻_𝐹={ℎ_𝐹0,ℎ_𝐹1,ℎ_𝐹2,…,ℎ_(𝐹[𝐵−1]) } and                               𝐻_𝑀={ℎ_𝑀0,ℎ_𝑀1, ℎ_𝑀2, …,ℎ_(𝑀[𝐵−1]) }.


In [76]:
HF=np.zeros(B).astype('int32');
HF

/home/usherbond/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':


array([[[[[[0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           ..., 
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0]],

          [[0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           ..., 
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0]],

          [[0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           ..., 
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0]],

          ..., 
          [[0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           ..., 
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0],
           [0, 0, 0, ..., 0, 0, 0]],

          [[0, 0, 0, ..., 0, 0, 0],
        

In [82]:
def BuildHistogramClassifier(X,T,B,xmin,xmax):
    HF=np.zeros(B).astype('int32');
    HM=np.zeros(B).astype('int32');
    binindices=(np.round(((B-1)*(X-xmin)/(xmax-xmin)))).astype('int32');
    for i,b in enumerate(binindices):
        if T[i]=='Female':
            HF[b]+=1;
        else:
            HM[b]+=1;
    return [HF,HM]
                

The enumerate() function adds a counter to an iterable.<br>

So for each element in cursor, a tuple is produced with (counter, element); the for loop binds that to row_number and row, respectively.

In [90]:
elements2 = ('a', 'b', 'c')
elements = ('foo', 'bar', 'baz')
for b in elements:
    print b

foo
bar
baz


In [87]:
for count, elem in enumerate(elements):
     print count, elem

0 foo
1 bar
2 baz


In [94]:
for count, elem2 in enumerate(elements2):
    for count, elem in enumerate(elements):
        print count, elem2, elem

0 a foo
1 a bar
2 a baz
0 b foo
1 b bar
2 b baz
0 c foo
1 c bar
2 c baz


In [83]:
B=32
xmin = np.amin(X)
xmax = np.amax(X)

In [81]:
# trying the output of bin index
binindices=(np.round(((B-1)*(X-xmin)/(xmax-xmin)))).astype('int32');
binindices

array([18, 24, 18, ..., 17,  8, 12], dtype=int32)

In [85]:
XT = BuildHistogramClassifier(X,T,B,xmin,xmax);
XT

[array([   3,    5,   12,   24,   44,  101,  163,  260,  404,  549,  693,
         869, 1076, 1013,  951,  823,  695,  494,  299,  217,  110,   58,
          20,   12,    5,    0,    0,    0,    0,    0,    0,    0], dtype=int32),
 array([  0,   0,   0,   0,   0,   0,   0,   0,   1,  10,  14,  53, 117,
        241, 369, 500, 700, 787, 849, 882, 873, 779, 610, 432, 274, 155,
         83,  38,  24,   5,   3,   1], dtype=int32)]

In [59]:
def Apply1DHistogramClassifier(queries,HF,HM,xmin,xmax):
    #alen returns the lenght
    B=np.alen(HF);
    binindices=np.clip((np.round(((B-1)*(queries-xmin)/(xmax-xmin)))).astype('int32'),0,B-1);
    countF=HF[binindices];
    countM=HM[binindices];
    resultlabel=np.full(np.alen(binindices),"Indeterminate",dtype=object);
    #this is marked as indeterminated now and later will be marked as male or female
    #here is the logic of machine learning, these are resulting in array of boolean
    indicesF=countF>countM;
    indicesM=countM>countF;
    resultlabel[indicesF]="Female";
    resultlabel[indicesM]="Male";
    resultprob=countF/(countF+countM);
    return resultlabel, resultprob

In [71]:
#B=np.alen('dddd')

# binindices=np.clip((np.round(((queries)/10)).astype('int32'),0,10))
#B=np.alen(queries)
#B
B = np.round(queries/10)
B

array([ 6.,  6.,  6.,  7.,  8.,  8.])

In [55]:
list=[1,2,3,4,5,6]
#Given an interval, values outside the interval are clipped to the interval edges. 
# For example, if an interval of [0, 1] is specified, values smaller than 0 become 0, 
# and values larger than 1 become 1.
B=np.clip(list,2,4)
B

array([2, 2, 3, 4, 4, 4])

In [58]:
# numpy.full(shape, fill_value, dtype=None, order='C')[source]
# Return a new array of given shape and type, filled with fill_value.
B=np.full((2, 2), 10)
B

array([[ 10.,  10.],
       [ 10.,  10.]])

In [44]:
def pdf(x,mu,sigma):
    return (1/(np.sqrt(2*np.pi)*sigma))*np.exp(-0.5*(((x-mu)/sigma)**2))

In [ ]:
def Apply1DBayesianClassifier(queries,muF,MuM,sigmaF,SigmaM,NF,NM):
    w=1;
    countF=
    countM=
    resultlabel=
    indicesF=
    indicesM=
    resultlabel
    

Write Back to Excel file. Keep the excel file closed while writing to file.

In [41]:
writeExcelData([xmin,xmax],excelfile,'Classifiers - Full Data',1,2)
writeExcelData([HF],excelfile,'Classifiers - Full Data',5,3)
writeExcelData([HM],excelfile,'Classifiers - Full Data',6,3)
writeExcelData([muF,muM],excelfile,'Classifiers - Full Data',8,3)
writeExcelData([sigmaF,sigmaM],excelfile,'Classifiers - Full Data',11,3)
writeExcelData([NF,NM],excelfile,'Classifiers - Full Data',14,3)
writeExcelData([resultHprob],excelfile,'Classifiers - Full Data',18,2)
writeExcelData([resultBprob],excelfile,'Classifiers - Full Data',19,2)

IndexError: list index out of range

Partial Data Sheet

In [ ]:
writeExcelData([xmin,xmax],excelfile,'Classifiers - Partial Data',1,2)
writeExcelData([HF50],excelfile,'Classifiers - Partial Data',5,3)
writeExcelData([HM50],excelfile,'Classifiers - Partial Data',6,3)
writeExcelData([muF50,muM50],excelfile,'Classifiers - Partial Data',8,3)
writeExcelData([sigmaF50,sigmaM50],excelfile,'Classifiers - Partial Data',11,3)
writeExcelData([NF50,NM50],excelfile,'Classifiers - Partial Data',14,3)
writeExcelData([resultHprob50],excelfile,'Classifiers - Partial Data',18,2)
writeExcelData([resultBprob50],excelfile,'Classifiers - Partial Data',19,2)